# Build Spec for AWS CodeBuild CI TF 2.4.x CPU and GPU Containers
# Containers Used:
    # Note: The public DLC is not yet available so this buildspec is currently consuming a custom built container

version: 0.2
env:
  variables:
    run_pytest_pytorch: "disable"
    run_pytest_mxnet: "disable"
    run_pytest_tensorflow: "disable"
    run_pytest_tensorflow2: "enable"
    run_pytest_xgboost: "disable"
    run_pytest_profiler: "enable"
    run_integration_pytest_pytorch: "disable"
    run_integration_pytest_mxnet: "disable"
    run_integration_pytest_tensorflow: "disable"
    run_integration_pytest_tensorflow2: "enable"
    run_integration_pytest_xgboost: "disable"
    # below needs to be enabled
    zero_code_change_test: "enable"
    # set code coverage flag
    code_coverage_smdebug: "true"
phases:
  install:
    commands:
        -  . config/change_branch.sh
        - su && apt-get update
        - apt-get install sudo -qq -o=Dpkg::Use-Pty=0 # silence output: https://askubuntu.com/a/668859/724247
        - sudo apt-get update -qq -o=Dpkg::Use-Pty=0
        - sudo apt-get install unzip -qq -o=Dpkg::Use-Pty=0
        - cd $CODEBUILD_SRC_DIR  && chmod +x config/protoc_downloader.sh && ./config/protoc_downloader.sh
        - pip install --upgrade pip==19.3.1
        - pip install -q pytest wheel pytest-html pre-commit awscli pytest-cov

  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR && pre-commit install && pre-commit run --all-files
      - cd $RULES_CODEBUILD_SRC_DIR && pre-commit install && pre-commit run --all-files

  build:
    commands:
      - echo "PRE COMMIT SUCCESSFUL"

  post_build:
    commands:
      - . $CODEBUILD_SRC_DIR/config/upload_on_end.sh
      - rm -rf $CODEBUILD_SRC_DIR/upload/$CURRENT_COMMIT_PATH
      - rm -rf $RULES_CODEBUILD_SRC_DIR/upload/$CURRENT_COMMIT_PATH
      - if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq 0 ]; then echo "ERROR BUILD FAILED " && exit 1 ; fi
      - if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq 1 ]; then echo "INFO BUILD SUCCEEDED !!! " ; fi
