# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smdebug/core/tfevent/proto/graph.proto

# Third Party
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# First Party
from smdebug.core.tfevent.proto import (
    node_def_pb2 as smdebug_dot_core_dot_tfevent_dot_proto_dot_node__def__pb2,
)
from smdebug.core.tfevent.proto import (
    versions_pb2 as smdebug_dot_core_dot_tfevent_dot_proto_dot_versions__pb2,
)

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="smdebug/core/tfevent/proto/graph.proto",
    package="smdebug",
    syntax="proto3",
    serialized_options=b"\n\030org.tensorflow.frameworkB\013GraphProtosP\001\370\001\001",
    serialized_pb=b'\n&smdebug/core/tfevent/proto/graph.proto\x12\x07smdebug\x1a)smdebug/core/tfevent/proto/node_def.proto\x1a)smdebug/core/tfevent/proto/versions.proto"f\n\x08GraphDef\x12\x1e\n\x04node\x18\x01 \x03(\x0b\x32\x10.smdebug.NodeDef\x12%\n\x08versions\x18\x04 \x01(\x0b\x32\x13.smdebug.VersionDef\x12\x13\n\x07version\x18\x03 \x01(\x05\x42\x02\x18\x01\x42,\n\x18org.tensorflow.frameworkB\x0bGraphProtosP\x01\xf8\x01\x01\x62\x06proto3',
    dependencies=[
        smdebug_dot_core_dot_tfevent_dot_proto_dot_node__def__pb2.DESCRIPTOR,
        smdebug_dot_core_dot_tfevent_dot_proto_dot_versions__pb2.DESCRIPTOR,
    ],
)


_GRAPHDEF = _descriptor.Descriptor(
    name="GraphDef",
    full_name="smdebug.GraphDef",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="node",
            full_name="smdebug.GraphDef.node",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="versions",
            full_name="smdebug.GraphDef.versions",
            index=1,
            number=4,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="version",
            full_name="smdebug.GraphDef.version",
            index=2,
            number=3,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\030\001",
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=137,
    serialized_end=239,
)

_GRAPHDEF.fields_by_name[
    "node"
].message_type = smdebug_dot_core_dot_tfevent_dot_proto_dot_node__def__pb2._NODEDEF
_GRAPHDEF.fields_by_name[
    "versions"
].message_type = smdebug_dot_core_dot_tfevent_dot_proto_dot_versions__pb2._VERSIONDEF
DESCRIPTOR.message_types_by_name["GraphDef"] = _GRAPHDEF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GraphDef = _reflection.GeneratedProtocolMessageType(
    "GraphDef",
    (_message.Message,),
    {
        "DESCRIPTOR": _GRAPHDEF,
        "__module__": "smdebug.core.tfevent.proto.graph_pb2"
        # @@protoc_insertion_point(class_scope:smdebug.GraphDef)
    },
)
_sym_db.RegisterMessage(GraphDef)


DESCRIPTOR._options = None
_GRAPHDEF.fields_by_name["version"]._options = None
# @@protoc_insertion_point(module_scope)
