# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smdebug/core/tfevent/proto/node_def.proto

# Third Party
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# First Party
from smdebug.core.tfevent.proto import (
    attr_value_pb2 as smdebug_dot_core_dot_tfevent_dot_proto_dot_attr__value__pb2,
)

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="smdebug/core/tfevent/proto/node_def.proto",
    package="smdebug",
    syntax="proto3",
    serialized_options=b"\n\030org.tensorflow.frameworkB\tNodeProtoP\001\370\001\001",
    serialized_pb=b'\n)smdebug/core/tfevent/proto/node_def.proto\x12\x07smdebug\x1a+smdebug/core/tfevent/proto/attr_value.proto"\xad\x01\n\x07NodeDef\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02op\x18\x02 \x01(\t\x12\r\n\x05input\x18\x03 \x03(\t\x12\x0e\n\x06\x64\x65vice\x18\x04 \x01(\t\x12(\n\x04\x61ttr\x18\x05 \x03(\x0b\x32\x1a.smdebug.NodeDef.AttrEntry\x1a?\n\tAttrEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.smdebug.AttrValue:\x02\x38\x01\x42*\n\x18org.tensorflow.frameworkB\tNodeProtoP\x01\xf8\x01\x01\x62\x06proto3',
    dependencies=[smdebug_dot_core_dot_tfevent_dot_proto_dot_attr__value__pb2.DESCRIPTOR],
)


_NODEDEF_ATTRENTRY = _descriptor.Descriptor(
    name="AttrEntry",
    full_name="smdebug.NodeDef.AttrEntry",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="key",
            full_name="smdebug.NodeDef.AttrEntry.key",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="value",
            full_name="smdebug.NodeDef.AttrEntry.value",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=b"8\001",
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=210,
    serialized_end=273,
)

_NODEDEF = _descriptor.Descriptor(
    name="NodeDef",
    full_name="smdebug.NodeDef",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="smdebug.NodeDef.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="op",
            full_name="smdebug.NodeDef.op",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="input",
            full_name="smdebug.NodeDef.input",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="device",
            full_name="smdebug.NodeDef.device",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="attr",
            full_name="smdebug.NodeDef.attr",
            index=4,
            number=5,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[_NODEDEF_ATTRENTRY],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=100,
    serialized_end=273,
)

_NODEDEF_ATTRENTRY.fields_by_name[
    "value"
].message_type = smdebug_dot_core_dot_tfevent_dot_proto_dot_attr__value__pb2._ATTRVALUE
_NODEDEF_ATTRENTRY.containing_type = _NODEDEF
_NODEDEF.fields_by_name["attr"].message_type = _NODEDEF_ATTRENTRY
DESCRIPTOR.message_types_by_name["NodeDef"] = _NODEDEF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NodeDef = _reflection.GeneratedProtocolMessageType(
    "NodeDef",
    (_message.Message,),
    {
        "AttrEntry": _reflection.GeneratedProtocolMessageType(
            "AttrEntry",
            (_message.Message,),
            {
                "DESCRIPTOR": _NODEDEF_ATTRENTRY,
                "__module__": "smdebug.core.tfevent.proto.node_def_pb2"
                # @@protoc_insertion_point(class_scope:smdebug.NodeDef.AttrEntry)
            },
        ),
        "DESCRIPTOR": _NODEDEF,
        "__module__": "smdebug.core.tfevent.proto.node_def_pb2"
        # @@protoc_insertion_point(class_scope:smdebug.NodeDef)
    },
)
_sym_db.RegisterMessage(NodeDef)
_sym_db.RegisterMessage(NodeDef.AttrEntry)


DESCRIPTOR._options = None
_NODEDEF_ATTRENTRY._options = None
# @@protoc_insertion_point(module_scope)
